%{
#include <stdio.h>
int yylex();
void yyerror(const char *s);
%}

%token NOUN ARTICLE VERB PREP

%%

SENTENCE: NOUN_PHRASE VERB_PHRASE { printf("PASS\n"); } | error { printf("FAIL\n"); };

NOUN_PHRASE: CMPLX_NOUN | CMPLX_NOUN PREP_PHRASE;

VERB_PHRASE: CMPLX_VERB | CMPLX_VERB PREP_PHRASE;

CMPLX_NOUN: ARTICLE NOUN;

CMPLX_VERB: VERB | VERB NOUN_PHRASE;

PREP_PHRASE: PREP CMPLX_NOUN;
%%
